# Generated by Django 4.0.4 on 2022-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcomplain', '0003_comaplain_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='comaplain',
            name='status',
            field=models.CharField(choices=[('solve', 'not solve')], default='green', max_length=6),
        ),
    ]
