# Generated by Django 4.0.4 on 2022-05-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcomplain', '0004_comaplain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comaplain',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Solved')], default='Pending', max_length=6),
        ),
    ]
