# Generated by Django 4.0.4 on 2022-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcomplain', '0005_alter_comaplain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comaplain',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Solved')], default=1),
        ),
    ]
